In [2]:
import numpy as np

# Step 2: Declare a 2D array
arr = np.array([
                [3, 2, 1], 
                [6, 5, 4],
                [9, 8, 7]])

# Step 3: Print the array
print("Original array:\n", arr)

# Step 4: Sort and flatten
arr = np.sort(arr, axis=None)

# Step 5: Reshape to 2D
arr = arr.reshape(3, 3)

# Step 6: Print reshaped array
print("\nReshaped and sorted array:\n", arr)

# Step 7: Update values
arr[0] += 5
arr[1] *= 2
arr[2] = np.square(arr[2])
print(arr[2])

# Step 8: Print updated array
print("\nUpdated array:\n", arr)

# Step 9: Get and print min and max
print("\nMinimum value in array:", np.min(arr))
print("Maximum value in array:", np.max(arr))

Original array:
 [[3 2 1]
 [6 5 4]
 [9 8 7]]

Reshaped and sorted array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
[49 64 81]

Updated array:
 [[ 6  7  8]
 [ 8 10 12]
 [49 64 81]]

Minimum value in array: 6
Maximum value in array: 81
