# Author: Willie M. Bonavente

In [1]:
import numpy as np

In [2]:
#  Declare a 2D array
arr = np.array([
                [3, 2, 1], 
                [6, 5, 4],
                [9, 8, 7]])

In [3]:
# Step 1: Print the declared two dimensional array
print(arr)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


In [4]:
# Step 2:Sort the two dimensional array
arr = np.sort(arr)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# and flatten it after the sorting
print(arr.flatten())

[1 2 3 4 5 6 7 8 9]


In [6]:
# Step 3: Reshape to 2D with 3 rows
arr = arr.reshape(3, 3)

In [7]:
# Step 4: After the reshaping print it
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
"""
Step 5: Add to value of 5 to the first row, 
        multiply 2 to the 2nd row, 
        square the third row.
"""

arr[0] += 5
arr[1] *= 2
arr[2] = np.square(arr[2])

In [9]:
# 6. Print the updated values of the two dimensional table.
print(arr)

[[ 6  7  8]
 [ 8 10 12]
 [49 64 81]]


In [10]:
# 7.	Get the minimum and maximum values of the two dimensional table.
print("Minimum Value: ",np.min(arr))
print("Maximum Value: ",np.max(arr))

Minimum Value:  6
Maximum Value:  81
